### ISSUE TITLE
Documentation Hyperlink not working 

### ISSUE THREAD

**Issue by bhanu-Bigdata** [JCDecaux/setl#100]
**Describe the bug**
I am trying to follow the documentation and I see the hyperlink specified for **Repository** https://github.com/JCDecaux/setl/wiki/Repository is not working. 

**Expected behavior**
I would expect the hyperlink to open.

**Comment by qxzzxq** [comment]
Thanks for the issue :) I forgot to modify these links when I was transferring the wiki. I will fix them

**Comment by qxzzxq** [comment]
hyperlinks are fixed

**Comment by bhanu-Bigdata** [comment]
Thanks.. its working 👍
