### ISSUE TITLE
Review Setl builder

### ISSUE THREAD

**Issue by maroil** [JCDecaux/setl#14]
DCContext builder should be able to parse spark related configuration from the config file when `setDCContextConfigPath` is called.

In a section like the following: 
```
context_config {
  spark {
    master_url = "url"
    app_env = ""
  }
}
```

**Comment by qxzzxq** [comment]
Setl will look by default the following configuration in the config file:

```
setl.config {
  spark {
    spark.default.parallelism = "200"
    spark.sql.shuffle.partitions = "200"  # set a bigger value if memory spills
  }
}
```
