### ISSUE TITLE
OSSRH deployment

### ISSUE THREAD

**Issue by qxzzxq** [JCDecaux/setl#20]
### Documentation
https://central.sonatype.org/pages/ossrh-guide.html

@maroil can you create a account in [Jira of OSSRH](https://issues.sonatype.org/projects/OSSRH/issues/OSSRH-53951?filter=allopenissues) and apply the deployer right?

After the permission grant, we can start configuring our deployment!

FYI, normally the **javadoc** and **source** maven plugin should already be configured correctly.

**Comment by maroil** [comment]
@qxzzxq I created the ticket [OSSRH-54027](https://issues.sonatype.org/browse/OSSRH-54027). Need your confirmation !

**Comment by qxzzxq** [comment]
pom file needs to be configured
