### ISSUE TITLE
Publish coverage report 

### ISSUE THREAD

**Issue by qxzzxq** [JCDecaux/setl#46]
Test coverage report is created with **scoverage** and can be found in `target/site/scoverage`. We can publish it into a public bucket

**Comment by maroil** [comment]
I just created a public bucket called jcd-datacorp-setl (url : http://jcd-datacorp-setl.s3-website.eu-west-1.amazonaws.com/).
I also gived CodeBuild the permission to write to this bucket. 
You can now use awscli to sync content of coverage in this bucket.
Please use a suffix (/coverage/) so the we can reuse it to publish other contents (documentation ...)

**Comment by qxzzxq** [comment]
The coverage report and api doc have been published (#51) 
http://jcd-datacorp-setl.s3-website.eu-west-1.amazonaws.com/snapshot/scaladocs/#com.jcdecaux.setl.Setl

http://jcd-datacorp-setl.s3-website.eu-west-1.amazonaws.com/snapshot/scoverage/
